// auto-generated by configen
// to add or remove properties, edit the mapping file: './configuration/AppEnvironment.map'.
// README: https://github.com/theappbusiness/ConfigGenerator/blob/master/README.md

import Foundation

class AppEnvironment {

  static let retryCount: Int = 3

  static let baseURL: String = "https://liveenvironment.com/"

}
